"use client";
import {assetUrl} from "@/lib/app-runtime";
import {useEffect,useRef,useState} from "react";
import {renderToStaticMarkup} from "react-dom/server";
import {Bike,Dog,Trees,Droplets,Wrench,Armchair,ArrowUpDown,Construction,Footprints,MapPin,TriangleAlert,Accessibility,ChevronUp,LocateFixed,Plus,Minus,Maximize,Layers,LoaderCircle,Check,Flag} from "lucide-react";
import {type Point,type Report,type Network,type RouteResult,PLACES,isObstacle} from "@/lib/routing";
import {KYIV_DISTRICTS,COVERAGE_BOUNDS} from "@/lib/region";
// Leaflet is vendored locally, so the map does not depend on a third-party script loader.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type LApi=any;
let library:Promise<LApi>|undefined;
function leaflet(){if(!library)library=new Promise((resolve,reject)=>{const el=document.createElement("script");el.src=assetUrl("vendor/leaflet.js");el.onload=()=>resolve((window as unknown as {L:LApi}).L);el.onerror=()=>{library=undefined;reject(new Error("Не вдалося завантажити карту"));};document.head.appendChild(el);});return library;}
function featureIcon(r:Report){if(r.kind==="toilet")return <span className="wc-symbol">WC</span>;if(r.kind==="bench")return <Armchair size={17}/>;if(r.kind==="dog_park"||r.kind==="pet_supply")return <Dog size={17}/>;if(r.kind==="cycleway"||r.kind==="bike_parking")return <Bike size={17}/>;if(r.kind==="bike_repair")return <Wrench size={17}/>;if(r.kind==="water")return <Droplets size={17}/>;if(r.kind==="park")return <Trees size={17}/>;if(r.kind==="steps")return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M3 20h5v-5h5v-5h5V5h3"/></svg>;if(r.kind==="lift")return <ArrowUpDown size={17}/>;if(r.kind==="surface")return <Footprints size={17}/>;if(r.kind==="temporary")return <Construction size={17}/>;return <TriangleAlert size={17}/>;}
export type MapHandle={zoom:(amount:number)=>void;fit:()=>void;coverage:()=>void;fly:(p:Point)=>void};
type Props={start:Point;end:Point;route:RouteResult|null;features:Report[];network:Network|null;onSelect:(r:Report)=>void;onPick:(p:Point)=>void;pickMode:string|null;location:Point|null;handleRef:React.MutableRefObject<MapHandle|null>;fitVersion:number};
export default function KyivMap({start,end,route,features,network,onSelect,onPick,pickMode,location,handleRef,fitVersion}:Props){
 const root=useRef<HTMLDivElement>(null);const instance=useRef<LApi>(null);const layers=useRef<{L:LApi;markers:LApi;paths:LApi;fallback:LApi;city:LApi}|null>(null);const latest=useRef({onSelect,onPick,start,end,route,pickMode});latest.current={onSelect,onPick,start,end,route,pickMode};
 const [ready,setReady]=useState(false);const[viewportVersion,setViewportVersion]=useState(0);const[error,setError]=useState("");const[tileProblem,setTileProblem]=useState(false);
 useEffect(()=>{if(!ready||!instance.current)return;const attribution='Точки місць: <a class="google-map-credit" translate="no" href="https://maps.google.com/" target="_blank" rel="noreferrer">Google Maps</a>';const map=instance.current;if(start.googlePlaceId||end.googlePlaceId)map.attributionControl.addAttribution(attribution);return()=>{map.attributionControl.removeAttribution(attribution);};},[ready,start.googlePlaceId,end.googlePlaceId]);
 useEffect(()=>{let canceled=false;let observer:ResizeObserver|undefined;leaflet().then(L=>{if(canceled||!root.current)return;const map=L.map(root.current,{zoomControl:false,attributionControl:true,minZoom:10,maxZoom:19,preferCanvas:true,maxBounds:[[50.14,30.12],[50.68,30.91]],maxBoundsViscosity:.8}).setView([50.4474,30.5196],15);instance.current=map;map.createPane("city-network").style.zIndex="350";map.createPane("coverage").style.zIndex="320";map.createPane("road-fallback").style.zIndex="300";map.attributionControl.setPrefix(false);map.on("moveend",()=>setViewportVersion(v=>v+1));
 const tiles=L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap</a>'}).addTo(map);let failures=0;tiles.on("tileerror",()=>{if(++failures>=3)setTileProblem(true);});tiles.on("tileload",()=>{failures=0;setTileProblem(false);});
 const fallback=L.layerGroup().addTo(map);L.geoJSON(KYIV_DISTRICTS,{pane:"coverage",style:{color:"#647895",weight:1.4,dashArray:"5 6",opacity:.65,fill:false},interactive:false}).addTo(map);
 const city=L.layerGroup().addTo(map);layers.current={L,fallback,city,paths:L.layerGroup().addTo(map),markers:L.layerGroup().addTo(map)};
 map.attributionControl.addAttribution('<a href="https://data.kyivcity.gov.ua/" target="_blank" rel="noreferrer">Міські дані: КМДА</a>');
 map.on("click",(e:{latlng:{lat:number;lng:number}})=>latest.current.onPick({...e.latlng,label:`Точка на карті (${e.latlng.lat.toFixed(4)}, ${e.latlng.lng.toFixed(4)})`}));
 const fit=()=>{const d=latest.current;const points=d.route?.coords||[[d.start.lat,d.start.lng],[d.end.lat,d.end.lng]];map.fitBounds(L.latLngBounds(points),{padding:[75,90],maxZoom:16,animate:true});};
 const coverage=()=>map.fitBounds([[COVERAGE_BOUNDS.south,COVERAGE_BOUNDS.west],[COVERAGE_BOUNDS.north,COVERAGE_BOUNDS.east]],{padding:[30,65]});
 handleRef.current={coverage,zoom:(n:number)=>map.setZoom(map.getZoom()+n),fit,fly:(p:Point)=>map.flyTo([p.lat,p.lng],16)};
 observer=new ResizeObserver(()=>map.invalidateSize());observer.observe(root.current);setReady(true);
 }).catch(e=>setError(e.message));return()=>{canceled=true;observer?.disconnect();instance.current?.remove();instance.current=null;handleRef.current=null;};},[handleRef]);
 useEffect(()=>{if(!ready||!layers.current)return;const{L,markers,city}=layers.current;markers.clearLayers();city.clearLayers();const map=instance.current;const occupied=new Set<string>();const ordered=[...features].sort((a,b)=>Number(!!a.source)-Number(!!b.source)||Number(b.kind==="toilet")-Number(a.kind==="toilet"));let shown=0;for(const r of ordered){if(r.lines?.length){for(const line of r.lines){const path=L.polyline(line,{pane:"city-network",color:"#15845e",weight:3,opacity:.8}).addTo(city);path.bindTooltip(document.createTextNode(r.title));path.on("click",(event:LApi)=>{L.DomEvent.stopPropagation(event);latest.current.onSelect(r);});}continue;}if(!map.getBounds().pad(.15).contains([r.lat,r.lng]))continue;const pixel=map.project([r.lat,r.lng],map.getZoom());const key=`${Math.round(pixel.x/44)},${Math.round(pixel.y/44)}`;if(occupied.has(key)&&r.source)continue;occupied.add(key);if(shown++>100)break;const utility=!isObstacle(r.kind);const node=document.createElement("div");node.className=`place-pin ${utility?"utility":"obstacle"} ${r.source?"osm-pin":"community-pin"}`;node.innerHTML=renderToStaticMarkup(featureIcon(r));node.title=r.title;const marker=L.marker([r.lat,r.lng],{icon:L.divIcon({className:"marker-wrapper",html:node,iconSize:[34,38],iconAnchor:[17,34]}),title:r.title,alt:r.title,keyboard:true,zIndexOffset:utility?100:50}).addTo(markers);marker.on("click",(event:LApi)=>{L.DomEvent.stopPropagation(event);latest.current.onSelect(r);});}},[ready,features,viewportVersion]);
 useEffect(()=>{if(!ready||!layers.current)return;const{L,paths}=layers.current;paths.clearLayers();if(route){L.polyline(route.coords,{color:"#ffffff",weight:10,opacity:.95,lineCap:"round",lineJoin:"round"}).addTo(paths);L.polyline(route.coords,{color:"#245bdd",weight:5,opacity:1,lineCap:"round",lineJoin:"round"}).addTo(paths);
 if(route.startGap>5)L.polyline([[start.lat,start.lng],route.coords[0]],{color:"#62799a",weight:3,dashArray:"3 7"}).addTo(paths);if(route.endGap>5)L.polyline([route.coords[route.coords.length-1],[end.lat,end.lng]],{color:"#62799a",weight:3,dashArray:"3 7"}).addTo(paths);
 const mid=route.coords[Math.floor(route.coords.length*.5)];L.marker(mid,{interactive:false,icon:L.divIcon({className:"route-label-marker",html:`<span class="route-map-label"><strong>${route.minutes} хв</strong><span>попередній маршрут</span></span>`,iconSize:[160,48],iconAnchor:[-18,24]})}).addTo(paths);
 }
 for(const[p,letter]of [[start,"А"],[end,"Б"]]as const){L.marker([p.lat,p.lng],{icon:L.divIcon({className:"endpoint-wrapper",html:`<div class="endpoint endpoint-${letter==="А"?"start":"end"}">${letter}</div>`,iconSize:[38,44],iconAnchor:[19,40]}),title:`${letter}: ${p.label}`,keyboard:true,zIndexOffset:500}).addTo(paths).bindTooltip(document.createTextNode(p.label),{direction:"top",offset:[0,-35]});}
 if(location)L.circleMarker([location.lat,location.lng],{radius:9,color:"white",weight:3,fillColor:"#245bdd",fillOpacity:1}).addTo(paths).bindTooltip("Ваше розташування");
 },[ready,route,start,end,location]);
 useEffect(()=>{if(ready&&fitVersion>0)handleRef.current?.fit();},[ready,fitVersion,handleRef]);
 useEffect(()=>{if(!ready||!layers.current)return;const{L,fallback}=layers.current;fallback.clearLayers();if(!tileProblem||!network)return;const nodes=new Map(network.elements.filter(e=>e.type==="node").map(e=>[e.id,e]));for(const w of network.elements){if(w.type!=="way"||!w.nodes||!w.tags?.highway)continue;const coords=w.nodes.map(id=>nodes.get(id)).filter(Boolean).map(n=>[n!.lat,n!.lon]);if(coords.length>1)L.polyline(coords,{pane:"road-fallback",color:/^(footway|path|steps)$/.test(w.tags.highway)?"#d1dccc":"white",weight:/^(footway|path|steps)$/.test(w.tags.highway)?2:7,interactive:false}).addTo(fallback);}for(const p of PLACES.slice(0,11))L.marker([p.lat,p.lng],{interactive:false,icon:L.divIcon({className:"fallback-place-label",html:renderToStaticMarkup(<span>{p.label}</span>),iconSize:[130,24]})}).addTo(fallback);fallback.bringToBack?.();},[ready,tileProblem,network]);
 return <><div ref={root} className={`leaflet-map ${pickMode?"picking":""}`} aria-label="Інтерактивна карта Києва. Точки маршруту також можна обрати у формі." />{!ready&&!error&&<div className="map-loading"><LoaderCircle className="spin"/><span>Відкриваємо Київ…</span></div>}{error&&<div className="map-loading"><TriangleAlert/><p>{error}</p><button onClick={()=>window.location.reload()}>Спробувати ще раз</button></div>}{tileProblem&&<p className="tile-notice">Фон карти недоступний. Показано наявну мережу доріжок.</p>}</>;
}
