"use client";
import {ArrowUpRight,Database,RefreshCw,Check,Info,LoaderCircle} from "lucide-react";
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {GOOGLE_MAPS_ENABLED} from "@/lib/google-places";
import {IS_STATIC_PAGES} from "@/lib/app-runtime";
import type {SourceData} from "@/lib/city-data";
import type {NetworkIndex} from "@/lib/network-client";
const date=(v?:string)=>v?new Date(v).toLocaleString("uk-UA",{day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}):"Не вказано";
export default function SourcesDialog({open,onOpenChange,sources,index,loading,error,onRefresh,onGoogle}:{open:boolean;onOpenChange:(v:boolean)=>void;sources:SourceData[];index:NetworkIndex|null;loading:boolean;error:string;onRefresh:()=>void;onGoogle:()=>void}){
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="app-dialog sources-dialog"><DialogHeader><div className="dialog-icon"><Database size={24}/></div><DialogTitle>Звідки дані на карті</DialogTitle><DialogDescription>Правий берег Києва · джерела даних і їхні обмеження.</DialogDescription></DialogHeader>
 <div className="sources-list"><section className="source-card"><h3>OpenStreetMap · мережа шляхів</h3><span className="source-status"><Check size={13}/>Збережено в застосунку</span><p>{index?`${index.ways.toLocaleString("uk-UA")} доріг і доріжок · ${index.districts.length} районів`:"Завантажуємо відомості про покриття…"}</p><small>Стан бази OSM: {date(index?.osm_timestamp)}</small><small>Підготовлено: {date(index?.retrieved_at)}</small><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap · ODbL<ArrowUpRight size={13}/></a></section>
 {sources.map(s=><section key={s.id} className="source-card"><h3>{s.name}</h3><span className={`source-status ${s.error||s.status==="unavailable"?"source-delayed":""}`}>
 {s.error||s.status==="unavailable"?<Info size={13}/>:<Check size={13}/>} {s.status==="unavailable"?"Джерело недоступне":s.status==="live"?"Отримано з джерела":s.status==="cache"?"Збережена копія":"Копія в застосунку"}</span>
 <p>{s.features.length} об’єктів на правому березі</p><small>Завантажено: {date(s.fetched_at)}</small><small>Оновлено джерелом: {date(s.updated_at)}</small>{s.error&&<p className="source-error">Не вдалося отримати нові дані. Дата збереженої копії вказана вище.</p>}<a href={s.url} target="_blank" rel="noreferrer">Відкрити міське джерело<ArrowUpRight size={13}/></a></section>)}
 <section className="source-card"><h3>Google Maps · відомості про місця</h3><span className={`source-status ${GOOGLE_MAPS_ENABLED?"":"source-delayed"}`}>{GOOGLE_MAPS_ENABLED?"За вашим запитом":"Ще не підключено"}</span><p>Пошук місць, фотографії, графік роботи й відомості про доступність входу, якщо вони є у Google.</p><small>Google не підтверджує прохідність усього маршруту. Картки завантажуються під час пошуку й не додаються до нашої бази перешкод.</small><button className="text-button" onClick={onGoogle}>Відкрити пошук Google Maps<ArrowUpRight size={14}/></button></section>
 <section className="source-card"><h3>Спостереження спільноти</h3>{IS_STATIC_PAGES?<><p>Додавання фото, повідомлень і підтверджень у цій версії недоступне.</p><small>Маршрути не враховують оперативні спостереження мешканців. Тимчасові перешкоди можуть бути відсутні на карті.</small></>:<><p>Фото, перешкоди та корисні місця від мешканців. Завантажуються перед кожною побудовою маршруту.</p><small>Роль автора вказується ним самостійно. Підтвердження не є незалежною перевіркою.</small></>}</section></div>
 {error&&<p className="inline-error" role="status">{error}</p>}<button className="primary-button" disabled={loading} onClick={onRefresh}>{loading?<LoaderCircle size={17} className="spin"/>:<RefreshCw size={17}/>} {loading?"Оновлюємо джерела…":"Оновити міські дані"}</button>
 <p className="small-muted">{IS_STATIC_PAGES?"Міські дані збережені разом із сайтом. Кнопка завантажує їх з опублікованої версії; вона не звертається до міських реєстрів напряму. Дати кожного джерела наведені вище.":"Міські дані перевіряються при відкритті та кожні 30 хвилин, доки сторінка активна. Копія з API використовується до 6 годин. Вигульні майданчики місто оновлює щороку."} Дата завантаження не означає перевірку стану на місці.</p>
 <p className="small-muted">Веломережа міста показана окремим шаром. Маршрути розраховуються за зв’язками й обмеженнями OSM. Межі: {index?.districts.map(d=>d.replace(" район","")).join(", ")}.</p>
 </DialogContent></Dialog>;
}
